language: python
python:
- '3.8'
before_install: python -m pip install poetry tox-travis
install: poetry install -v
script: tox
jobs:
  include:
    - stage: deploy
      python: "3.8"
      before_install: python -m pip install poetry
      install: skip
      script: skip
      before_deploy:
        - poetry version $(git describe --tags --exact-match --match="v*.*.*" | cut -b2-)  # fallback "" means, "0.0.0"
        - poetry config pypi-token.pypi $PYPI_TOKEN
      deploy:
        skip_cleanup: true  # so "poetry version" stays
        provider: script
        script: poetry publish --build
        on:
          tags: true

env:
  global:
    - secure: "J/To8I89fTdo0D+BjCPpYCQuN/n4QBjQL4tGpuFn9Pz1vnfnqMxrNLqkVvlmkt5P4N58UnpNk2+HYf57jDjCUGeBXG5+faFGnuf9M4qfLRqIeku2IaWl9ghymuiU0iSn2NTSMh/n14xzpEmLXF+2mBzqwHQS6H7Eifa3otAsK6rZstu7gq40p0hyldEE6wyVhzczf/4g2ldTAw3ZNxY/LYGqYbZEME1Y97B+p/krzGxdVwiwpTcf+Z+w4G80Fv7LchWzS4f6Gowcvmxc6dIUMBRHFGqQXBqmT2xhptYcax5MJufJgL8wQM4X+lUz8WO0e2bybN8MqhgnEkvbTjRNli/zlPcTxcz9fNRk2zzaaN8KJZxTrh19FiULlqRy3tf4U68TN4ZWbSuu5oaS/j619fVFUIZj7/401pCGR6AYyn/wOyAmGzL5NoD4DxIlwEBCu+MqY59UWWaMtfSK2ntVxtT10QHTBiGn9eIDvGVoNevr/LsuUKvpc2HIFkJKl54jdXKer2WMuT/uAUQLSig0UCmixNYm9Un51wHRSl3YMtB64GP7rA+5dfXVP5VTiIxXJGeIvR7mfXkQ8eDQXCUQIX45IUXwpZDrGUHjrbAH3sCO7J3FNf13y5BFsFY+3yIdZiNiGkxTWGFtGpxs5huDSQXM3j4U5Tu/kwFBrj6G3Is="
