# Pontoon likes each locale to have a directory. But importlib requires
# "__init.py__" in every directory we want to read files from. So we
# tell Pontoon locale paths are flat files, not directories.

[[paths]]
  reference = "cjwmodule/i18n/messages.pot"
  l10n = "cjwmodule/i18n/{locale}.po"
